FROM python:3.12-slim-bookworm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/ 

RUN mkdir -p /opt/sandbox
WORKDIR /opt/sandbox
COPY . . 

RUN uv sync

CMD uv run celery -A app.celery_app worker -B --loglevel=debug